target: part1.out part2.out part3.out part4.out iobound cpubound 

part1.out:
	gcc -Wall -g -o part1 part1.c


part2.out:
	gcc -Wall -g -o part2 part2.c 


part3.out: 
	gcc -Wall -g -o part3 part3.c 


part4.out:
	gcc -Wall -g -o part4 part4.c 


iobound: 
	gcc -o iobound iobound.c 


cpubound:
	gcc -o cpubound cpubound.c 



